name: release

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - run: echo 'asdf'
