name: release

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Save tag version for re-usage later on
        id: getVersion
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - run: docker build -t ghcr.io/komed-health/pwgen .

      - run: docker tag ghcr.io/komed-health/pwgen ghcr.io/komed-health/pwgen:${{ steps.getVersion.outputs.VERSION }}

      - name: Login to GitHub Cloud Registry
        run: echo ${{ secrets.ORG_GITHUB_CONTAINER_REGISTRY_TOKEN }} | docker login ghcr.io -u BorntraegerMarc --password-stdin

      - run: docker push ghcr.io/komed-health/pwgen
      - run: docker push ghcr.io/komed-health/pwgen:${{ steps.getVersion.outputs.VERSION }}
