name: release

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - run: echo ${{ steps.getVersion.outputs.VERSION }}

      - run: docker build -t ghcr.io/komed-health/pwgen .

      # - run: docker tag ghcr.io/komed-health/pwgen ghcr.io/komed-health/pwgen:d
